"""empty message

Revision ID: 338565c39b18
Revises: e08e1bb8a0a0
Create Date: 2023-10-07 13:50:01.445408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338565c39b18'
down_revision = 'e08e1bb8a0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
